version: '3.8'

services:

  db:
    image: mysql
    container_name: classroom_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: classroom
      MYSQL_USER: classroomuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - classroom-network

  backend:
    build:
      context: ./backend/
      dockerfile: docker/Dockerfile
    container_name: backend
    restart: always

    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/classroom?createDatabaseIfNotExist=true&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: classroomuser
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - classroom-network

  frontend:
    build:
      context: ./frontend/
      dockerfile: docker/Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - classroom-network

volumes:
  db_data:

networks:
  classroom-network:
    driver: bridge